### ISSUE TITLE
Is there any way to integrate with fog?

### ISSUE THREAD

**Issue by LukeCarlThompson** [N8python/n8ao#10]
Nice work on this, it's performing very well when testing so far.

One potential issue I'm encountering is that the AO effect is drawn over the top of any fog in the scene. I'm assuming because this effect is a screen space one it's not possible to actually draw it onto the material shaders before the fog. But I wondered if there was some depth information available and we could fade the opacity of the effect based on distance from the camera or something else that would give a reasonable approximation?

Is this kind of thing possible currently or any plans to implement?

**Comment by N8python** [comment]
Yes, I could modulate the effect by fog. This feature will be added in the next update.

**Comment by N8python** [comment]
Fog has been added!

**Comment by N8python** [comment]
<img width="1340" alt="Screen Shot 2023-06-13 at 11 31 23 AM" src="https://github.com/N8python/n8ao/assets/43304488/4d1c8d28-fb41-4f7c-9e8f-94afc06918a7">
Here's a picture of (overdone) bloom working with N8AOPass... try updating to 1.6.1.

**Comment by N8python** [comment]
Try - instead of this:
        this.effectPass = new gD(this.camera,this.aaEffect,this.brightnessContrastEffect,this.bloomEffect),
This:
        this.effectPass = new gD(this.camera,this.brightnessContrastEffect,this.bloomEffect, this.aaEffect),
        
 As the AA effect should come after everything.
 
 BTW this works with the latest version:
 ```js
    const composer = new EffectComposer(renderer);
    composer.addPass(new RenderPass(scene, camera));
    const n8aopass = new N8AOPostPass(
        scene,
        camera,
        clientWidth,
        clientHeight
    );
    composer.addPass(n8aopass);
    composer.addPass(new EffectPass(camera, new BloomEffect({
        luminanceThreshold: 0.0,
        intensity: 5.0
    }), new SMAAEffect({
        preset: SMAAPreset.ULTRA
    })));
    ```

**Comment by LukeCarlThompson** [comment]
Thank you for that. I see what the difference is now.

I'm using a selective bloom technique where I set the bloom effect luminance threshold to 1 and then set the materials I want bloom on to be` toneMapped: false` and the `emissiveIntensity` to a high value like 8. Then only those objects will have the bloom effect applied. Could it be that because the N8aopass goes first it renders a tone mapped output or some other way of clipping the colours back into the normal range of 0 - 1?

If you try this code sandbox and comment out the aoPass on line 79 you will see the bloom effect is visible again.

[https://codesandbox.io/s/sparkling-cdn-qslj6y?file=/src/index.js](https://codesandbox.io/s/sparkling-cdn-qslj6y?file=/src/index.js)

**Comment by N8python** [comment]
N8AO uses non-float render targets... that could definitely be the problem. Next update (will be released tonight/early tmrw) will add support for floating render targets.

**Comment by N8python** [comment]
Should be fixed now.

**Comment by LukeCarlThompson** [comment]
Yep, it's working great. Thanks so much really appreciate the great work and fast updates!
