### ISSUE TITLE
Issues w/ AO at large distances from the origin

### ISSUE THREAD

**Issue by liuyehua** [N8python/n8ao#11]
When I integrated your AO plug-in into the map application, I found that the Ambient occlusion function failed. My test found that my model was located at a position far from the (0,0,0) point, such as (13487434.764630988, -6.397349827894406, -3741689.4034150834). At this time, my camera's observation position would also be at a large number of positions. When I moved the model to the (0,0,0) point, the Ambient occlusion function could work normally again, I think if the position of the camera is too large, it will cause the function to fail?

**Comment by liuyehua** [comment]
and i find if camera far number too big also have some problem, Is it because of the precision of webgl Floating-point arithmetic?

**Comment by N8python** [comment]
Upon further investigation... this IS an issue with N8AO - I'm doing stuff in world space instead of view space. Will be fixed in next release.

**Comment by N8python** [comment]
<img width="1409" alt="Screenshot 2023-06-15 at 1 02 53 PM" src="https://github.com/N8python/n8ao/assets/43304488/b0c9f16c-9144-4f7a-8436-814ddaa5234f">
Computed a trillion units out from the center.

**Comment by N8python** [comment]
Should be fixed now.
