### ISSUE TITLE
excluding objects

### ISSUE THREAD

**Issue by sheley1998** [N8python/n8ao#12]
Thank you for your amazing work! Would it be possible to exclude certain objects from AO? I have several PNG Sprites that have transparent backgrounds. the AO effect makes the transparent backgrounds "visible". Would be great if I could exclude these sprites from the AO pass.

**Comment by N8python** [comment]
Use an "alphaTest" to discard fragments with low alpha. If it doesn't write to the depth buffer, it won't generate AO.

**Comment by sheley1998** [comment]
that works, thanks! Is there something I can do to stop AO from obscuring emissive objects with selective bloom applied?

**Comment by N8python** [comment]
Apply bloom after AO, increase intensity of bloom, disable depth write on bloom-ed objects. Lots of different ways.

**Comment by sheley1998** [comment]
thanks, gonna give it a try
