### ISSUE TITLE
when camera far number too big have some problem...

### ISSUE THREAD

**Issue by liuyehua** [N8python/n8ao#13]
I am developing a map application based on three. js, and I need to set the camera far number very big ,such as 1e10, 
At this point, the color of distant objects will turn black, such as "sky.js“, and I don't know what happened...

> normal 
<img width="998" alt="image" src="https://github.com/N8python/n8ao/assets/27567569/ee4682ca-321f-4e50-88a9-3011599eb95e">

> with ao
<img width="791" alt="image" src="https://github.com/N8python/n8ao/assets/27567569/4008d17d-4071-43d7-a228-5cb1c1e7d40b">

**Comment by N8python** [comment]
Looking into it. Will follow up when I have a lead on what's causing it!

**Comment by N8python** [comment]
Should be fixed with the most recent push (far values well into 1e30+ are supported now)

**Comment by liuyehua** [comment]
> Should be fixed with the most recent push (far values well into 1e30+ are supported now)

thank you
