### ISSUE TITLE
N8AO + Bloom doesn't work when multisampling enabled

### ISSUE THREAD

**Issue by stockto2** [N8python/n8ao#15]
I have a pmndrs/postprocessing setup that looks like this:

RenderPass
N8AOPass #1
N8AOPass #2
EffectPass with Bloom + SMAA

With composer.multisampling set to 0, it works as expected. If I set multisampling to anything other than 0, both N8AOPass #2 and the Bloom pass stop producing any results. (As if they're disabled.)

You mentioned in discord that multisampling sometimes causes artifacts with SSAO, but it would be nice to have the option.

**Comment by N8python** [comment]
Looking into it...

**Comment by N8python** [comment]
But generally, anything that uses depth textures and MSAA is finicky.

**Comment by N8python** [comment]
I'm not sure why this is happening... it seems that the render target swap/clear that occurs between passes is somehow erasing the depth texture, but ONLY when msaa is happening. Incredibly weird.

**Comment by N8python** [comment]
@mrdoob @varunsec - Any idea what could be causing this?

**Comment by vanruesc** [comment]
Does this only happen with this combination of effects or does it also break when using only N8AO? Try using only a `DepthEffect` with MSAA enabled and check if the depth texture looks correct (might need to adjust near/far to see depth).

**Comment by N8python** [comment]
Good idea!
