### ISSUE TITLE
Hi, I just found out when open halfRes with true, the ao in map also have some same problem....

### ISSUE THREAD

**Issue by liuyehua** [N8python/n8ao#16]
```
        this.n8ao = new N8AOPass(this.scene, this.camera, this.width, this.height);
        this.n8ao.configuration.gammaCorrection = true;
        this.n8ao.configuration.halfRes = true;
        this.composer.addPass(this.n8ao);
```

<img width="1080" alt="image" src="https://github.com/N8python/n8ao/assets/27567569/9ccfbec1-28b4-4c49-a6d9-24520a58a08d">

**Comment by N8python** [comment]
I'm not sure what you mean from that one image...

**Comment by liuyehua** [comment]
> I'm not sure what you mean from that one image...

The old problem  on https://github.com/N8python/n8ao/issues/14, But this time it happened when i set "halfRes" with TRUE

**Comment by N8python** [comment]
Try version 1.6.8.

**Comment by N8python** [comment]
That should work.
