### ISSUE TITLE
AO from single side materials

### ISSUE THREAD

**Issue by whitecad** [N8python/n8ao#17]
Hello, my wall materials side is  THREE.FrontSide, when i move camera to outside of room, AO calculate wrong, sample picture is attached, how we can ignore single side materials for AO,

best regards,

![image](https://github.com/N8python/n8ao/assets/128173321/c6b5c760-8e8b-4d24-bf02-0af57192737e)

**Comment by N8python** [comment]
Try `.depthWrite = false` on the material. More details on twitter.
