### ISSUE TITLE
Option to accumulate over multiple frames

### ISSUE THREAD

**Issue by harrycollin** [N8python/n8ao#21]
Hi, would it be possible to add an option to accumulate AO over multiple frames? Some models look quite bad with lower quality settings (especially light surfaces) & cranking up the quality isn't always an option for lower end devices. I would love to help on this but my knowledge on GLSL is lacking 😄

**Comment by N8python** [comment]
I get why you're asking but I am strongly against adding temporal reprojection to the library as it would make things much more complicated, add overwhelming amounts of smearing, and requires exepensive-to-generate motion vectors. It would compromise performance just as much.

However, I would by open to making it so the camera could accumulate AO over multiple frames when frozen - as a toggleable setting for like... static viewing. Would you be interested in that?

**Comment by harrycollin** [comment]
> accumulate AO over multiple frames when frozen

Actually this is what I meant :D The option to accumulate when the camera is static would be great!

**Comment by N8python** [comment]
That should theoretically be doable - the issue is that it would require setting up a seperate render target and piping the AO through that... should be possible though. I'll get to it for the 1.8 release. Should be added within the month.

**Comment by N8python** [comment]
This should enable taking just ~4 samples a frame and getting results that look better then current ultra settings in less than a second - assuming stationary camera & scene.
<img width="1507" alt="Screenshot 2024-01-16 at 8 26 45 PM" src="https://github.com/N8python/n8ao/assets/43304488/f5125bba-537a-4112-86d8-5
<img width="1505" alt="Screenshot 2024-01-16 at 8 26 54 PM" src="https://github.com/N8python/n8ao/assets/43304488/569ba13c-3efb-418e-b176-1e20e009adac">
6dee322b462">

(Top is w/ accumulation, bottom w/out. Same perf cost)

**Comment by N8python** [comment]
<img width="1511" alt="Screenshot 2024-01-16 at 8 28 53 PM" src="https://github.com/N8python/n8ao/assets/43304488/595b0558-32b0-4561-8ec5-09f531341abf">
W/out it for reference.

**Comment by harrycollin** [comment]
This is really nice!

**Comment by N8python** [comment]
Commited.

**Comment by harrycollin** [comment]
Just updated the package on my side. Looks great! The accumulated AO is very good, for some scenes it completely changed the look for the better (as per your recommendation to set ```denoiseRadius: 0```). 

I tried experimenting with a mixed quality approach. Where I'd set the quality to the "Low" config while the camera was moving, then switching to your recommended config for accumulation when static. I was hoping to have a smooth transition but it looks like the frame gets cleared as soon as accumulation kicks in. Although stepping though the N8AOPass.ts I couldn't see this happening. 

Do you know what this could be?

**Comment by N8python** [comment]
Ah... I set it up so the accumumlation WOULD be cleared if you change the settings of N8AO... as the old samples have been invalidated. Wdym cleared? Like all the AO dissapears?

**Comment by harrycollin** [comment]
The behaviour you've described aligns with what I'm seeing to be honest. The static AO comes back quickly but there is a noticeable transition between dynamic and static AO. I'm going to see if I can configure this to achieve a smooth transition.
