### ISSUE TITLE
Debug Mode Question / Issue

### ISSUE THREAD

**Issue by jteppinette** [N8python/n8ao#24]
I am seeing that my `lastTime` is sometimes double what my entire total frame render time is? How is this possible?

I am running at 60FPS, but the `lastTime` variable in debug mode is showing `20-30ms` which would put me out of 60FPS.

Also, thank you so much for this incredible work. I have been trying everything available for literally years and this is the first thing to actually work and have good documentation! Kudos!

**Comment by N8python** [comment]
That is incredibly strange - it would likely indicate that the timing queries are somehow being desynced from the frame update loop. If you are running at 60FPS, discard `lastTime` - it relies on using gpu timing queries which are asynchronous and unreliable.

**Comment by jteppinette** [comment]
@N8python Thank you for your response!
