### ISSUE TITLE
My buffer is not being cleared

### ISSUE THREAD

**Issue by pailhead** [N8python/n8ao#28]
![image](https://github.com/N8python/n8ao/assets/4681282/4edf0169-71fc-4fa8-ae8f-f318e7c9b3f4)

Basically i have this:
```
    this._renderer.clear();
    this._composer.render();
```

And this:
```
    const composer = new EffectComposer(this._renderer);
    const renderPass = new RenderPass(this.scene, this.activeCamera);
    composer.addPass(renderPass);
    const ssaoPass = new N8AOPass(this.scene, this.activeCamera, window.innerWidth, window.innerHeight);
    composer.addPass(ssaoPass);
```
I just swapped out the other ssao pass, and removed a couple of others from the composer. Im not sure which target i need to be clearing. This is three's own `EffectComposer`.

**Comment by N8python** [comment]
Don't use the renderpass with the N8AO pass. JUST use the ssaoPass.
