### ISSUE TITLE
material.clone is not a function

### ISSUE THREAD

**Issue by jakobhenner** [N8python/n8ao#3]
very excited about this little package and it works perfectly — well almost!

- using `postprocessing`
- latest versions of postprocessing and three

works great when I'm applying it to a GLB model but in another scene with an OBJ, throws an error:

```
material.clone is not a function
    at OverrideMaterialManager.cloneMaterial (postprocessing.esm.js:5373:1)
    at OverrideMaterialManager.setMaterial (postprocessing.esm.js:5398:1)
    at new OverrideMaterialManager (postprocessing.esm.js:5315:1)
    at new RenderPass (postprocessing.esm.js:5525:1)
```

not the biggest deal, wanted to redo that scene either way, just wanted to let you know!

**Comment by N8python** [comment]
That appears to be an issue with the RenderPass - not with this library specifically!

**Comment by jakobhenner** [comment]
Using the latest version! 

If I remove the n8ao pass, the scene renders fine with other "native" postprocessing effects.
Realise this is not a lot to go on, so feel free to close the issue!

**Comment by N8python** [comment]
Are you perhaps using an `overrideMaterial` - if so, how?

**Comment by CodyJasonBennett** [comment]
This is because of the hacky normal pass which overrides materials with a `MeshStandardMaterial`. If you're using react-postprocessing make sure to specify `<EffectComposer disableNormalPass />`.

**Comment by jakobhenner** [comment]
@CodyJasonBennett @N8python I feel stupid, thx!
