### ISSUE TITLE
AO receiver but not casting

### ISSUE THREAD

**Issue by Ben-Mack** [N8python/n8ao#30]
Thank you for creating this powerful lib!

For example in your official example, I want to enable AO for the torus only, not the building, but torus should be able to cast AO to the building, not just on itself.
(It is like the building only receive AO, but not casting)

![image](https://github.com/user-attachments/assets/4c9208d3-423a-4ac5-a0da-1133fcd764d9)

Please give me some guidance if you have any idea, I'd much appreciate your response!

**Comment by N8python** [comment]
This has been added in release 1.8.4:

You can also simply have an object not receive AO at all (this requires rendering it twice, so it is not recommended for performance-critical applications) by setting cannotReceiveAO to true in the object's userData:

mesh.userData.cannotReceiveAO = false;
