### ISSUE TITLE
I found that when there are linesegment models in the scene, there are many jagged lines that cannot be eliminated...

### ISSUE THREAD

**Issue by liuyehua** [N8python/n8ao#6]
I found that when there are linesegment models in the scene, there are many jagged lines that cannot be eliminated...

> code
    let child = [];
    sponza.traverse(object => {
        if (object.material) {
            object.material.envMap = environment;
            child.push(object)   
        }
    })
    child.forEach(m=>{
        m.add(new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry,90)))
    })

> such as 

<img width="1274" alt="image" src="https://github.com/N8python/n8ao/assets/27567569/5b369b81-37f1-425f-9e69-23578b6f88d0">

**Comment by liuyehua** [comment]
Both SMAA and fxaa are invalid

**Comment by N8python** [comment]
I'm afraid post-processing ambient occlusion and (in general) SMAA/FXAA don't work with just lines. Disabling dpeth-write on the lines should help the AO work though.

**Comment by liuyehua** [comment]
thank you, it works
